### ISSUE TITLE
Is there any reason this plugin is uses an outdated Gradle version?

### ISSUE THREAD

**Issue by tkgregory** [bmuschko/gradle-docker-plugin#1019]
This plugin currently uses Gradle 5.2.0 from February 2019. 

I'm sure you're aware that the current version Gradle version is 7.1.

I'm currently writing a review of this plugin and am confused as to why the Gradle version is so out of date.

Did I miss something? Thanks :)

P.S. If there's no such reason, I'm happy to do the update when I get time

**Comment by bmuschko** [comment]
Gradle 5.2.0 is the minimal binary-compatible version the plugin supports. That's why the plugin is built with that version. Choosing a newer version may break binary compatibility with older versions.

All of this does not mean that the plugin won't be compatible with a newer or the latest version of Gradle. Optimally, the test suite should be executed with multiple Gradle versions to ensure all permutations. At the moment, we are not doing it simply because of the implementation effort and increased build times.
