### ISSUE TITLE
DockerSaveImage should probably never be up-to-date

### ISSUE THREAD

**Issue by Vampire** [bmuschko/gradle-docker-plugin#1071]
`DockerSaveImage` depends on the state of the Docker daemon as input.
It should probably never be up-to-date, and thus annotated with `@UntrackedTask`.
I have a `DockerBuildImage` task that builds the docker image from the Docker file and then a `DockerSaveTask` that saves it to a file that I then release as artifact.
But as long as none of the inputs or outputs of the task changed, it is considered up-to-date even if the state on the Docker Daemon changed due to a rebuild.

**Comment by Vampire** [comment]
Actually the same with the `DockerBuildImage` task.
The main output is in the docker daemon.
But the only output considered is the `imageIdFile`.

**Comment by Vampire** [comment]
Ah, I just have seen that you kind of do it for `DockerBuildImage` already, just that you only verify whether the image with the id in the file is still available, not whether it has the expected tags, that should maybe be checked too, but I'll open a separate issue for that.

**Comment by bmuschko** [comment]
I agree that it will likely more correct to simply let Docker handle caching concerns for the operation. There are far too many corner cases that can lead to incorrect or undesired results. I don't think making the task up-to-date will gain much build performance anyways. I would say let's change the code so that the task is never up-to-date.

**Comment by Vampire** [comment]
Now that I changed mind and hopefully properly implemented the up-to-dateness? 🙈
