### ISSUE TITLE
Can I use within a CI container?

### ISSUE THREAD

**Issue by mflorence99** [bmuschko/gradle-docker-plugin#119]
I love this plug in and I'd like to use it -- but our CI itself runs in a container. I'm aware of the issues of running docker-in-docker, but it seems like I should be able to reference the same Docker that runs the CI container. I can't get beyond 'Connection refused' though.

So I run the CI container with an additional `-v` flag to allow it to reference the Docker certs:

```
-v $DOCKER_CERT_PATH:/xxx \
```

`xxx` is just an easy-to-type placeholder until and if I can get this to work. Then inside of my `build.gradle` I try to configure Docker like this:

```
docker {
  url = 'http://localhost:2376'
  // or 'http://192.168.99.100:2376'
  // or anything else I can thing of
  certPath = new File('/xxx')
}
```

I'm stumped. I know the plugin is running _inside_ `docker-machine` but I think [jpetazzo](http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/) is showing that this is possible.

I understand this isn't a bug, but any help greatly received!

**Comment by cdancy** [comment]
@mflorence99 we do the same thing here quite successfully I might add. Because gradle-docker-plugin is built on top of https://github.com/docker-java/docker-java you don't need to configure the docker extension here everytime. Instead, and what we do, is to configure the image/container AOT through the "~/.docker.io.properties" file. In there you want to add the property "docker.io.url=http://<docker-daemon-ip>:<docker-daemon-port>". The docker-java project has all the information you need to configure this property file once and never again. This should get you using dockers remote API successfully.

The real fun comes when you want to start mounting volumes from within a container :) That was an interesting problem we solved in an interesting way...

**Comment by mflorence99** [comment]
@cdancy You left me in suspense ... let me absorb chapter 1 of your story first, then I'll come back for more :) Many thanks -- I'll try to get this working

**Comment by bmuschko** [comment]
@mflorence99 Sorry, I don't have any input to this topic.

**Comment by bmuschko** [comment]
I am going to close the issue. Feel free to continue the discussion here.
