### ISSUE TITLE
Multi-platform support

### ISSUE THREAD

**Issue by big-andy-coates** [bmuschko/gradle-docker-plugin#1197]
Hi,

Love the `com.bmuschko.docker-remote-api` plugin and have been using it for a number of years without any issues. 

I now have a requirement to either:

1. create a multi-platform image, or
2. create multiple images that differ only by platform

The former seems to require the use of `docker xbuild`, which doesn't seem to be supported by the plugin. See https://docs.docker.com/build/building/multi-platform/.

The later seems like it might be possible via the `platform` property on `DockerBuildImage` task, but there is zero documentation that I can find around this.

Would love to be able to continue to use the plugin to build either multi-platform images, or at least images with specific target architectures.

Thanks.

**Comment by bmuschko** [comment]
Buildx is currently not supported by the Docker daemon. You can find a discussion of this topic [here](https://github.com/bmuschko/gradle-docker-plugin/issues/967).

The `platform` property is documented in the [API documentation of the task](https://bmuschko.github.io/gradle-docker-plugin/current/api/com/bmuschko/gradle/docker/tasks/image/DockerBuildImage.html#getPlatform()). We have a [functional test](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImageFunctionalTest.groovy#L102-L142) for this but I don't remember why I ignored it. I believe the test case was failing for some reason even though the image creation works in isolation. I think that's why I didn't add something to the textual documentation.

**Comment by big-andy-coates** [comment]
Yep, saw the api docs, but it wasn't enough information for me to piece together a working solution. 

:+1: to the discussion topic. Totally understand your time is limited, and appreciate your efforts.

I found a work around, so this is not urgent for me.  It was more I wanted to flag up missing docs. If I couldn't get it to work, likely others failed too.

Feel free to close this issue, or use it to track the missing docs...

**Comment by big-andy-coates** [comment]
Actually, my workaround didn't work around anything.  So my question still kinda stands - is it possible to build an image for one platform on another using the plugin? For example, can I build an `linux/arm64` image on a `linux/amd64` machine, or vice-versa?

...and if so... how?

My own attempts have failed.  I'm locally on an `linux/arm64` machine. I've set the `platform` to `linux/amd64` and pass in an `TARGET_PLATFORM` build argument, and used this to supply a `--platform` param on my `FROM` statement in the Dockerfile:

```kotlin
val buildAppImage = tasks.register<DockerBuildImage>("buildAppImage") {
    dependsOn("prepareDocker")
    platform.set("linux/amd64")
    buildArgs.put("APP_NAME", project.name)
    buildArgs.put("APP_VERSION", "${project.version}")
    buildArgs.put("TARGET_PLATFORM", dockerBuildImage.platform)
    images.add("ghcr.io/specmesh/${rootProject.name}-${project.name}:latest")
    images.add("ghcr.io/specmesh/${rootProject.name}-${project.name}:${project.version}")
}
```

```Dockerfile
ARG TARGET_PLATFORM

FROM --platform=$TARGET_PLATFORM eclipse-temurin:11-jre-focal

...
```

Unfortunately, this fails with:

```
Could not build image: failed to get destination image "sha256:8ad748c72ef12441730505c6fe180567d48c30bd959f3c1e3525f6e2cac4c5ff": image with reference sha256:8ad748c72ef12441730505c6fe180567d48c30bd959f3c1e3525f6e2cac4c5ff was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8
```

Not sure what the deal is here.  I thought the point of setting `--platform` in `FROM` was to set a platform specific base image.

**Comment by bmuschko** [comment]
Checking in on this. Were you able to implement your use case in the meantime?

**Comment by AlexGII** [comment]
Hey! Does anyone have a chance to build multi-platform image? Maybe some other solutions, would be appreciated.

**Comment by bmuschko** [comment]
On CI, I would probably just go with the [BuildKit container image](https://github.com/moby/buildkit/blob/master/docs/multi-platform.md) instead of using the remote API. Much easier. On developer machines, you likely won't need to build multi-platform container images anyway. They are meant to be published.
