### ISSUE TITLE
Ability to ignore failures on gradle tasks

### ISSUE THREAD

**Issue by joshwils82** [bmuschko/gradle-docker-plugin#131]
It would be nice to have the ability to ignore failures on the gradle tasks (especially when removing images/containers).  The main use case for this is the ability to write a clean task that attempts to remove the built container/image during the gradle build.  Adding a flag would allow the build to continue in the event one of the images/containers is not present.

**Comment by bmuschko** [comment]
You can already provide your only logic e.g. by overriding the existing logic. Here's an example:

    class ExceptionCatchingDockerRemoveContainer extends DockerRemoveContainer {
        @Override
        void runRemoteCommand(dockerClient) {
           try {
               super.runRemoteCommand(dockerClient)
           } catch(Exception e) {
               logger.error "Unable to remove container. Continuing..."
           }
        }
    }

There's nothing built in otherwise.

**Comment by cdancy** [comment]
@joshwils82 we do something similar in that we override each task that we don't want to fail (much like @bmuschko states above), check the exception message, and if relevant print out a message saying "container does not exist", or something more relevant, otherwise re-throw exception.

I do happen to agree that having this as part of the plugin would be beneficial. I guess the problem comes down to: which exceptions do we check for and not fail on? Do we want an umbrella "catch-all"? The sounds bad IMO. I guess we would want to do something like what I noted above and check for ONLY the exception that is relevant to the task otherwise re-throw. Perhaps a flag that defaults to current behavior but if a property, say "failOnError = false" (a la Ant style) set somewhere higher above is set (maybe AbstractDockerRemoteApiTask?), we can interrogate the specific tasks exception and fail/proceed accordingly.

@bmuschko thoughts?

**Comment by bmuschko** [comment]
I think the most flexible way to handle this would be with a help for some sort of execution handler. To make this work we could introduce a new interface. Each task would have a default implementation as instance variable which whose method is used in the task action. The default implementation would contain the actual call to Docker Java. If a user doesn't like the default behavior then she/he can simple provide their own implementation. The concept is similar to what I had in mind with the `ResponseHandler`. Given that Docker Java changed their API to callbacks we'd have to rethink this anyway.

**Comment by cdancy** [comment]
@bmuschko +1. Sounds like it may make sense to close the issue and put this feature on the backlog until sometime AFTER dockerjava integration. @joshwils82 you could still proceed with the quick-and-easy solution I provided above and roll your own release locally. We do it here and then ocassionally rebase against master and it works well for us.

**Comment by joshwils82** [comment]
Ok that works.  thx @bmuschko @cdancy

**Comment by neiljbrown** [comment]
Hi, 

We'd like to use the plugin's Container related tasks to automate the deployment of our services, specifically implement the following steps -
 - pull a tagged image (check we can pull it, before proceeding with following steps).
 - stop the named container, if it exists and is running
 - optionally remove the named container, it it exists
 - create the container / run the newly pulled image.

We've run into the same limitation in the plugin as reported in this issue, namely the stop (or restart, or inspect) container custom tasks all treat the container not existing as a fatal error. Whereas, we would like to continue in this particular error case.  

What's the status of this feature request? Was a separate issue raised for as part of adding it to the backlog? If not, what's the best way of getting it considered - raising a new issue, and tagging it as a feature request? 

Thanks.

**Comment by cdancy** [comment]
#153 has been created to address these concerns.

**Comment by neiljbrown** [comment]
@cdancy - Hi, many thanks for following up on this and creating the issue to capture the work. Much appreciated.
