### ISSUE TITLE
Is there a way to skip DockerPushImage task when there is no change in the source code?

### ISSUE THREAD

**Issue by ximinggao** [bmuschko/gradle-docker-plugin#208]
Currently even if there is no change in the source code the DockerPushImage task will still be executed, and pushing docker images to the docker registry is a time-consuming task, so in order to speed up the gradle build procedure, is there a way to detect changes in the source code and skip pushing if there is no change?

**Comment by cdancy** [comment]
There are many gradle-type things you can do here to short-circuit the execution of a given task. You could try using an `onlyIf` closure to proceed, only if, the given source is not up-to-date or some logic is not true. Coding for such things is the responsibility of the developer and not this plugin. If you feel otherwise, or have any other questions, feel free to re-open.
