### ISSUE TITLE
Should be able to get imageId from DockerPullImage

### ISSUE THREAD

**Issue by dlvenable** [bmuschko/gradle-docker-plugin#293]
As shown on the Wiki, if we wish to chain together building an image and creating a container from it, we can use the `getImageId` property from DockerBuildImage.

`targetImageId { buildMyAppImage.getImageId() }`

However, there is no similar property for DockerPullImage. Thus we cannot start a container from a pulled image. I think this would be a very useful feature for using remote repositories.

**Comment by cdancy** [comment]
@dlvenable if you look over our tests we have lots of examples which do this very thing. Here is a snippet to get you going:

```
            task pullImage(type: DockerPullImage) {
                repository = 'alpine'
                tag = '3.4'
            }
            task createContainer(type: DockerCreateContainer) {
                dependsOn pullImage
                targetImageId { pullImage.repository+":"+pullImage.tag }
                cmd = ['/bin/sh','-c',"echo Hello World"]
            }
```

**Comment by cdancy** [comment]
@dlvenable yeah I see what you're saying. The problem comes down to how do we know if you're building image with a known tag vs using a Dockerfile? I suppose the solution would/could look something like:

1. Build image however you want
2. Inspect image getting tag/repo/etc
3. `DockerPullImage` could then depend on `DockerInspectImage` and set the relevant properties programmatically.

I think this is really the only sane solution unless I'm missing something. If you're up for it you could send in a PR that exposes the required variables for `DockerInspectImage`.

**Comment by dlvenable** [comment]
Thanks @cdancy for the explanation in your original comment. That actually worked for what we were trying to achieve.

I think perhaps the problems with that approach are: it is not entirely obvious (that could be solved with documentation), and there is not a direct connection between the previous pull image and the current create container.

**Comment by cdancy** [comment]
Closing issue. I'll update the docs to address the confusion found here.
