### ISSUE TITLE
Implement `onComplete` and `onNext` reactive-stream methods

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#305]
My thinking is we implement the aforementioned methods as closures on tasks much like we did with `onError`. How I see them working is like so:

onComplete: implemented in the same location as `onError`, meaning within [AbstractDockerRemoteApiTask](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractDockerRemoteApiTask.groovy), and execute once the task has finished without errors.

onNext: implemented in the same location as `onError`, meaning within [AbstractDockerRemoteApiTask](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractDockerRemoteApiTask.groovy), and execute once the task has finished without errors BUT uses the returned value of `runRemoteCommand` (which currently is void but will change to T or Object) as the input to this closure. The returned value is the output object of the docker-java invocation. We usually use this to set various properties for folks to query after the fact (thinking DockerInspectContainer here) but now we will allow them to query the object at runtime for whatever they need.

@orzeh thoughts?

**Comment by orzeh** [comment]
@cdancy I agree with `onComplete` which is quite straightforward, but with `onNext` I would prefer different approach. I think we should provide our custom [ResultCallback]( docker-java/src/main/java/com/github/dockerjava/api/async/ResultCallback.java) implementation and _forward_ `onNext` events to handlers/closures registered in given task. This behavior should be _opt-in_ i.e. only if `onNext` closure is defined otherwise fallback to current solution (logging). This implementation will be IMO more  _reactive_ :smiley: 

I've started some work on this and will make PR soon. Then you can have a look and we will decide what direction to choose.

BTW I think we should target it to `3.1.x` as it adds some new features.

**Comment by cdancy** [comment]
Sounds good. I'll wait for you future PR to talk further on this. I have use-cases for both which is why I brought this up. I released a new version yesterday with `onError` and was able to remove a fair amount of code from our stuff here. Implementing these 2 methods would allow me to further remove a fair amount more which is always good in my book ;)

**Comment by orzeh** [comment]
OK, @cdancy take a look at #307

**Comment by cdancy** [comment]
Closing as functionality has been merged.
