### ISSUE TITLE
Support Docker 1.12 Swarm mode

### ISSUE THREAD

**Issue by mam0nth** [bmuschko/gradle-docker-plugin#322]
The plugin already supports container operations, it is nice also to support docker service operations. In the hype of microservices+docker, I think this feature is one of the missing feature here. It can be used primarily in CI/CD.

**Comment by cdancy** [comment]
@mam0nth you will have to open an ISSUE with [docker-java](https://github.com/docker-java/docker-java) to support this as we build on top of that library.

**Comment by arun-gupta** [comment]
@cdancy Already opened https://github.com/docker-java/docker-java/issues/710

**Comment by cdancy** [comment]
@arun-gupta we're just waiting on those guys now...

**Comment by KostyaSha** [comment]
What exactly do you want to use from swarm mode features? Mixing build tools with deployment tools is bad pattern that nobody using in production. Penalty in java APi usage makes sense only for development time.

**Comment by arun-gupta** [comment]
@KostyaSha I think it may be about whether docker-java api can be targeted to a Swarm mode manager? API compatibility? I'm sure @cdancy can provide more details.

**Comment by KostyaSha** [comment]
My research end that for jenkins builds swarm mode is useless, that also proved docker devs. Most people blindly jumping on docker features without understanding them. That's why i'm interested in knowing use cases. Swarm mode is prepared, but everybody who wants help disappear when hear about tests. So usually all delays happens until i or somebody else create test case and fix found bugs.

**Comment by cdancy** [comment]
> but everybody who wants help disappear when hear about tests.

@KostyaSha we face the same problem here and I believe every maintainer of a project does :)

I don't consider this plugin something that should be used ONLY for CI related purposes. We have use-cases here where that is the case but the majority of what we use this plugin for is to make it stupid-simple for developers to stand up our platform (which is a handful of containers) by simply invoking: `./gradlew startOurApp`. We've recently had discussions around the use of swarm in that if for folks who don't have docker installed locally (or who just don't want to go through the hassle of setting up virtual-box/etc), which is a fair number at this point, instead point them to a docker swarm behind-the-scenes, stand them up our app, and have it work just like if they were doing so against docker running natively. This would be very useful and something I'd eventually like to see in this plugin.

**Comment by KostyaSha** [comment]
you don't need install swarm for managing it. Docker cli is available for all platforms and even from gradle it pretty simple to wrap single command. Jenkins has huge experience with wrapping CLI vs API. So you can't live without API when you do a lot of java routines, but it enough i.e. to run single commands. Even easier with doing it from shell. Penalty - ability to catch some markers/cases. That's why i'm asking about real use cases.

**Comment by gesellix** [comment]
For me using the shell implies a specific platform - or several `if/else` cascades. Natively using an api makes the client flexible. That's not a specific use case, but more a general kind of philosophy.

**Comment by gesellix** [comment]
If I get you right @KostyaSha , you're interested in use cases so that the api is driven by actual needs. That's where I fully agree. There's one question, though: do we "technically adapt" an external api like the Docker engine or do we focus on use cases only? You see the difference right here in the Gradle Docker plugin, where there's one level of "technical adaption" and another more opinionated level to make specific use cases more convenient.

**Comment by KostyaSha** [comment]
My point is that with gradle there is no work stoppage i simply made custom tasks in gradle script and moved forward. I'm asking about use cases for better understanding technical side implementation.

**Comment by cdancy** [comment]
Closing as I'm not sure if there is anything else here to discuss. Feel free to re-open if necessary.

**Comment by KostyaSha** [comment]
It almost done... https://travis-ci.org/docker-java/docker-java/builds/229155863?utm_source=github_status&utm_medium=notification

**Comment by cdancy** [comment]
Thanks for the update @KostyaSha! Devs at my work that have upgraded to the latest and greatest docker have been pinging me about this issue. Would be great to get `3.0.10` in.

**Comment by KostyaSha** [comment]
3.0.10 has last PR that has feature + fix for args. Then will release. When swarm test become green will cycle master to 3.1

**Comment by cdancy** [comment]
@KostyaSha is it an issue where the dev doesn't want to clean up the tests? I know you (as all maintainers have) hit that issue before and I jumped in and cleaned things up. If that's the case here, and you don't have the time, just scream my way and I can see about cleaning up the remaining tests.
