### ISSUE TITLE
Document how to run the functional tests locally

### ISSUE THREAD

**Issue by jmewes** [bmuschko/gradle-docker-plugin#333]
It would be nice, if you'd document in your [README](https://github.com/bmuschko/gradle-docker-plugin/blob/master/README.asciidoc) file how to run the functional tests locally. I think an example for the Docker configuration and calling of the Gradle task from the command-line would be sufficient to be able to configure the IDE as well.

Currently I don't know comply with the [TestPrecondition](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/testSetup/groovy/com/bmuschko/gradle/docker/TestPrecondition.groovy)s and the tests are being ignored.

I tried to start a Docker registry locally but felt kind of lost and gave up:
```
# https://docs.docker.com/registry/
docker run -d -p 5000:5000 -p 2375:2375 --name registry registry:2

# https://docs.docker.com/engine/reference/api/docker_remote_api/
curl --unix-socket /var/run/docker.sock http://localhost:2375/info
```

For my pull request (https://github.com/bmuschko/gradle-docker-plugin/pull/332) I had rely on the [CI](https://app.snap-ci.com/bmuschko/gradle-docker-plugin/pull/332/logs/defaultPipeline/1/Initial?back_to=build_history) only to make sure that my test passes.

### Related issues
- Example of Functional Tests (https://github.com/bmuschko/gradle-docker-plugin/issues/161)
- Execute functional tests using HTTPS instead of plain HTTP (https://github.com/bmuschko/gradle-docker-plugin/issues/149)
- Docker client is configured with specific API version (https://github.com/bmuschko/gradle-docker-plugin/pull/159)
- Create Vagrant box used for functional testing (https://github.com/bmuschko/gradle-docker-plugin/issues/148)
- Can't run integration tests (https://github.com/bmuschko/gradle-docker-plugin/issues/48)
- Specify port bindings when starting a container (https://github.com/bmuschko/gradle-docker-plugin/pull/38)

**Comment by orzeh** [comment]
@jmewes did you read [this](https://github.com/bmuschko/gradle-docker-plugin/blob/master/README.asciidoc#executing-the-plugins-test-suite-with-custom-configuration)? I think this is sufficient. If you have some ideas how to improve it feel free to submit PR or discuss it here.

**Comment by cdancy** [comment]
@jmewes please submit a PR if you think the docs surrounding how to run tests can be improved. @orzeh and myself may be narrow sighted in that we've been working with the code for so long it just makes sense to us. If you think there is something you can add to help developers come on board easier than by all means speak up and/or provide a PR to discuss! ;)

**Comment by jmewes** [comment]
@orzeh Yes, I read this but I am still not able to execute the tests. When I call this (on Linux/Fedora25), the build will pass even though I have modified the assertions in a way that they must fail.

```
docker run -d -p 5000:5000 --name registry registry:2
./gradlew build -DdockerServerUrl=http://localhost:2375 -DdockerPrivateRegistryUrl=http://localhost:5000
```

([full console output](http://pastebin.com/FGvyKe5J))

In the IDE I am getting a notice that the test is being ignored.

```
/usr/lib/jvm/java-1.8.0/bin/java ...

Test ignored.

Process finished with exit code 0
```

The reason is that I don't know how to comply with a the required preconditions.

So my problem is that I have no idea where to start the investigation for the reason that the tests are skipped. I am feeling a bit confused by the all details. It's new to me to use Docker via `http://localhost:5000` and that there are some certificates for it for any reason. I have also never run my own Docker registry and now it is mentioned for a reason I don't understand. Also it might be a cause why the tests are not running.

@cdancy  That's a nice attitude. However, I cannot make a pull request and suggest a better structure as long as it doesn't run on my machine. The knowledge gap here is that you are probably working with the Gradle/Docker/Groovy infrastructure for year and I am kind of an beginner in those areas and just need this particular feature in our build infrastructure.

**Comment by cdancy** [comment]
@jmewes aaaahhhh I see where you're confusion is coming in. You're not actually executing the `functionalTest` task which is analogous to "live" or "integration" tests. Try switching out `build` for `functionalTest` and see how that fares.

**Comment by orzeh** [comment]
@jmewes Functional testing this plugin is not an easy task because it has broad functionality, communicates with other software via network and so on. Therefore its testing harness is a little bit complicated. I don't think it should be fully covered in a README file as it is composed of tools and techniques well known to most developers. That being said I will give you here some details so you can grasp the idea and learn something new.

This plugin sends commands to Docker daemon which listens either on non-networked Unix socket or HTTP one. The latter can be secured by TLS (see [docs](https://docs.docker.com/engine/security/https/)). In our case - for tests - we do not require TLS to simplify things. Additionally we provide [Vagrant](https://www.vagrantup.com/) box which automates installing and configuring Docker engine (see [Vagrantfile](https://github.com/bmuschko/gradle-docker-plugin/blob/master/vagrant/Vagrantfile)) on developer machine. This box runs Docker daemon listening on `tcp://0.0.0.0:2375` and one container with [Docker Registry](https://docs.docker.com/registry/), which is used to test pushing images to private registry. It exposes its API on port 5000 which is bind to host port 5000 (thus `http://localhost:5000` is passed in `-DdockerPrivateRegistryUrl`).

Vast majority of tests for this plugin are written as a [Spock](http://spockframework.org/) specifications. Functional tests are annotated with [`@Require`](http://spockframework.org/spock/docs/1.1-rc-3/extensions.html#_requires) to avoid tests failures when running in environment without reachable Docker daemon. [TestPrecondition](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/testSetup/groovy/com/bmuschko/gradle/docker/TestPrecondition.groovy) and [TestConfiguration](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/testSetup/groovy/com/bmuschko/gradle/docker/TestConfiguration.groovy) classes are used to check if Docker daemon and Image Registry are available. You can tweak it if you have either of them in your infrastructure.

Personally I use Vagrant to setup test environment.

I hope it is now more clear. Feel free to asks further questions if I've missed something.

**Comment by jmewes** [comment]
@cdancy Thanks for considering an update of the documentation. Maybe you'd find [this blog post](http://blog.thefrontiergroup.com.au/2013/05/writing-a-good-readme/) useful for inspiration.

Unfortunately, using the `functionalTest` task resulted in a successful build even though I have modified the assertions in a way that is should fail.

```
janux@ultrabook-jm gradle-docker-plugin]$ git diff
diff --git a/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImageFunctionalTest.groovy b/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImageFunctionalTest.groovy
index fc16ade..46cbcfa 100644
--- a/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImageFunctionalTest.groovy
+++ b/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerBuildImageFunctionalTest.groovy
@@ -28,7 +28,7 @@ class DockerBuildImageFunctionalTest extends AbstractFunctionalTest {
         def result = buildAndFail('buildImage')
 
         then:
-        result.output.contains("aaa: no such file or directory")
+        result.output.contains("aaa: no such xxx or xxx")
     }

[janux@ultrabook-jm gradle-docker-plugin]$ docker run -d -p 5000:5000 --name registry registry:2
[janux@ultrabook-jm gradle-docker-plugin]$ ./gradlew functionalTest -DdockerServerUrl=http://localhost:2375 -DdockerPrivateRegistryUrl=http://localhost:5000
```

@orzeh Thank you for the clarification. It makes perfect sense not to explain basic technologies in your README. However, it would be nice if you explain the dependencies and configuration like you did above. See https://github.com/bmuschko/gradle-docker-plugin/pull/336 .

Ideally, there would be also a short Bash snippet which I can paste into the terminal to run the tests. (I don't know if this is feasible in this case.)

**Comment by orzeh** [comment]
@jmewes are you using local Docker daemon? Does it responds to `http://localhost:2375/info`? Because that is required to execute `DockerBuildImageFunctionalTest`.

Why don't you try using Vagrant if you have problems in setting up local environment by yourself?

Hint:
````bash
$ vagrant up
$ ./gradlew functionalTest
````

**Comment by cdancy** [comment]
@orzeh this has been a bug of sorts ever since we moved to `tcp|unix` for the protocol. User should not have to have a daemon listening on` http://localhost:2375`. [Created a story to track this](https://github.com/bmuschko/gradle-docker-plugin/issues/337). I'll try and knock it out this weekend.

**Comment by jmewes** [comment]
@orzeh Yes, the local Docker daemon is running and it given out some details for this command.

`curl --unix-socket /var/run/docker.sock http://localhost:2375/info`

Actually I don't care how to run the tests. Vagrant is fine. I didn't try it because I have never really used it and was reluctant to figure out workarounds like this https://github.com/mitchellh/vagrant/issues/6873 to get it working.

With the Vagrant box it is now it is working to run the tests both from Gradle and IDE. Thanks.

```
$ cd vagrant/
$ vagrant up --provider=virtualbox
$ ./gradlew functionalTest
```
See second commit in https://github.com/bmuschko/gradle-docker-plugin/pull/336 .

**Comment by cdancy** [comment]
Functionality now exists within master.
