### ISSUE TITLE
add DockerSaveImage and DockerLoadImage

### ISSUE THREAD

**Issue by joanmarian** [bmuschko/gradle-docker-plugin#395]
It would be very helpful to have tasks in this plugin that implement the equivalent of 
(after docker pull image) docker save image | gzip > name.tar.gz
and 
docker load image < name.tar.gz

**Comment by orzeh** [comment]
@joanmarian `docker-java` library, which is used by this plugin under the hood, has these capabilities. Wolud you be interested in sending PR?

**Comment by cdancy** [comment]
@orzeh this is a developer that works with me and we have a use-case to export/import a given image. As she is just coming up to speed on docker, and this plugin, and doesn't know her way around too well yet, I advised her to open the ISSUE here to see if anyone else would want to take on the work and if not we can add it to our backlog to knock out at some later date. I have plans to walk her through at some point how to add this feature just don't have the time at the moment.

If anyone else in the community is looking for a small story/contribution to make this would be a great starting point.

**Comment by fhoeben** [comment]
I would appreciate the feature!

**Comment by ReillyProcentive** [comment]
This feature would be very useful to us as well. We use Gitlab CI and persist the Docker source image to the cache on every build so that we can avoid having to download it each time (Gitlab CI uses the Docker DinD image which loses it's own built in cache on every build).

We currently do this with Docker commands but it would be nice to use the Gradle plugin here so that we could use Gradle for every build step.

**Comment by orzeh** [comment]
@ReillyProcentive @fhoeben I'll try to implement this in near future. Stay tunned!
