### ISSUE TITLE
DockerCreateContainer.targetImageId to allow GStrings

### ISSUE THREAD

**Issue by rkrisztian** [bmuschko/gradle-docker-plugin#513]
Following does not work:

```groovy
    targetImageId { "selenium/standalone-firefox${imageVariant}:2.53.0" }
```

Because I get:

```none
org.codehaus.groovy.runtime.GStringImpl cannot be cast to java.lang.String
```

Following does:

```groovy
    targetImageId { "selenium/standalone-firefox${imageVariant}:2.53.0" as String }
```

Small problem, and I ask it just for convenience. It is non-intuitive in the Gradle world that I have to cast.

**Comment by cdancy** [comment]
@rkrisztian yeah this is a known issue with groovy more than anything else. It's _supposed_ to do the String transformation when passing to a normal java library but seems to fail every now and then for whatever reason. The solution that you took is correct and what I personally do here. Within the plugin we _could_ do this in every spot ourselves where we reach out to a normal java library but there are a lot of points we'd have to hit and because their is an easy enough solution we simply haven't tackled it.

If anyone reading this wants to send in a PullRequest to do so we'd be happy to review and accept it.
