### ISSUE TITLE
Add option to DockerSaveImage task for image compression

### ISSUE THREAD

**Issue by scottresnik** [bmuschko/gradle-docker-plugin#565]
### Expected Behavior
Add a property to the DockerSaveImage task, e.g. "compressImage", that when set to true would compress the image to be saved using GZip.  The default setting would be false to be consistent with existing behavior.

### Current Behavior
There is no such setting on the DockerSaveImage task.  Currently images are saved as a tar.

### Context
Currently I zip up images using Gradle for transport to a remote docker container.  Compression drops the size of my image enough to make it worth my while.

### Steps to Reproduce (for bugs)
Not really applicable.

### Your Environment
Not a bug.

**Comment by cdancy** [comment]
@scottresnik hmmm ... we build upon the `docker-java` library which in turn is just a wrapper around OOTB docker commands. I don't think docker supports compression by default in their commands at least last time I checked they did not and the spirit of this library is to be/create gradle wrappers around those same commands.

How are you doing things now? Do you have a code snippet you can share or care to send in a PR so that we can see what you're talking about? Indeed tar files are not compressed and are just a packaged version of files and so can be quite big and having something like this might make sense.

**Comment by scottresnik** [comment]
Right now, I'm using the gradle zip task.  The tar task allows gzip compression, but it ended up creating a gzipped tar of a tar which is a bit of a mess.

I have the code done already, I can create a PR.

**Comment by cdancy** [comment]
Closing as this functionality has now been merged to master.
