### ISSUE TITLE
Can't start container (Invalid Argument)

### ISSUE THREAD

**Issue by antony** [bmuschko/gradle-docker-plugin#60]
Hi There,

Fantastic plugin - looks like exactly what we need.

When I'm using the DockerStartContainer task, I end up with the following output in the console:

> Cannot start container cd582a584b9864ac750d0a5361481e77e4cd3cf94dd31e136710e93f94dd5e73: write /sys/fs/cgroup/cpuset/docker/cd582a584b9864ac750d0a5361481e77e4cd3cf94dd31e136710e93f94dd5e73/cpuset.cpus: invalid argument

My tasks look like:

task createEventSourceContainer(type: DockerCreateContainer) {
    targetImageId { 'remmelt/docker-event-store:latest' }
}

task runEventSource(type: DockerStartContainer) {
    dependsOn createEventSourceContainer
    targetContainerId { createEventSourceContainer.getContainerId() }
    println "Running up event source docker container"
}

task stopEventSource(type: DockerStopContainer) {
    println "Stopping event source docker container"
    targetContainerId { createEventSourceContainer.getContainerId() }
}

A bit of googling shows the following bug:

https://github.com/docker/docker/issues/7941

is it possible that your own client suffers from the same bug?

**Comment by bmuschko** [comment]
What I understand from the Docker issue is that this apparently happens if you send `Cpuset` with the value `null`. I'd think that this is fixed with a newer version of Docker. Can you please try to upgrade?

As a side note: My plugin uses Docker Java as client. So if there's an issue, you'd need to address is there. The task `DockerStartContainer` doesn't allow for setting `Cpuset` at the moment, so I assume it uses whatever Docker Java sends as default value.

**Comment by bmuschko** [comment]
@antony Any feedback from your end?

**Comment by antony** [comment]
Hi @bmuschko 

Apologies - I haven't had a spare minute to look at this, it was a timeboxed spike for a client and we haven't continued in that direction just yet.

I'll try to get a minute to upgrade the Docker version and see if I can provide you any feedback.

Cheers,
Antony

**Comment by bmuschko** [comment]
OK, I am going to close the issue for now. Feel free to reopen.
