### ISSUE TITLE
Switch communication with Docker daemon to Spotify library

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-docker-plugin#688]
### Expected Behavior

All functionality is using [Spotify's Docker client](https://github.com/spotify/docker-client). Optimally, there's no change for the end user. The API stays the same. I believe the Spotify binary already [shades external libraries](https://github.com/spotify/docker-client#a-note-on-shading) making it possible to avoid have to rely on the thread context classloader in this plugin.

### Current Behavior

The plugin uses [Docker Java](https://github.com/docker-java/docker-java). We are currently [shading the libraries required by Docker Java](https://github.com/project-aries/docker-java-shaded) which adds another step of indirection to avoid classpath issues as Gradle does not run plugins in their own classloader.

### Context

Docker Java releases new version very infrequently making it hard to be able to incorporate any changes. Switching over the internal library probably requires multiple days of work.

**Comment by bmuschko** [comment]
I guess that would be possible. I'd rather rip off the bandade and get it all done at once. Maybe we can just create remote branch and work on it together? I am sure we'd know pretty quickly if there's missing functionality in the Spotify library.

**Comment by KostyaSha** [comment]
> Docker Java releases new version very infrequently making it hard to be able to incorporate any changes.

Have you ever ask to release what you need? 

> I believe the Spotify binary already [shades external libraries](https://github.com/spotify/docker-client#a-note-on-shading) making it possible to avoid have to rely on the thread context classloader in this plugin.

They had fake shading, maybe now they got how to shade everything. Correct docker-java shading example is available for years in my jenkins plugin. Jersey doesn't allow processing  streams and they doesn't want to change anything (i raised emails about unifying projects) because they support project only for their production needs. So that's all sounds like a step back for a project.

**Comment by bmuschko** [comment]
> Have you ever ask to release what you need?

I haven't been super involved in the project in the past two years or so. Only recently have I picked up more work. I can't speak for my team mates here but we feel like Docker Java releases have only come out very infrequent. Another issue I see is that the current version has been on a RC cycle for a very long time and breaking changes have been introduced even between RC releases. As an outsider, this gives me the impression that 1) the project isn't moving very fast, 2) bugs are lingering and that's why there's no final release. Again, this is an outside perspective and might reflect reality.

Hopefully, we are not giving you the wrong impression. I am very grateful for your work, @KostyaSha. Without Docker Java, this plugin wouldn't exist in the first place so we are standing on the shoulders of giants. I am sure life can get busy which means less involvement from your end, less features and bugfixes. We totally get that. Please don't see our comments here as criticism per se. We are hoping that our comments may lead to an improved process on both ends.

Here's what I'd wish for the future:

1. Releases happen more frequently without us having to ask necessarily. I'd be all in favor for a new final release for every new feature or bugfix.
2. No more breaking changes in between RCs. Based on semantic versioning that should really only happen between minor versions.
3. This is more a feature request from my end: less dependencies on external libraries from Docker Java. Usually, no problem but we'll have to maintain a shaded version of Docker Java more or less because of Gradle's lack of classloader isolation.

> They had fake shading, maybe now they got how to shade everything. Correct docker-java shading example is available for years in my jenkins plugin. Jersey doesn't allow processing streams and they doesn't want to change anything (i raised emails about unifying projects) because they support project only for their production needs. So that's all sounds like a step back for a project.

I am not quite sure I fully understand all of your comments here. It likely requires a bit more context. We'll probably evaluate the Spotify library at some point and see if it could work for us. In the meantime, we'll stick with Docker Java.

**Comment by KostyaSha** [comment]
RC are giving ability for depending projects to try changes and provide feedback. Some projects saying they will do it, but then didn't reply. Some even silently switched. 
Breaking changes are needed to fresh code. It's unreal to have compatibility because docker also making constant changes. 
Without correct classloader (the same situation in jenkins) you will be forced to do shading. It's impossible to sync all used libraries. Shading is works fine with multi-module project structure. The example is my project https://github.com/KostyaSha/yet-another-docker-plugin 
In future i want split docker-java into modules so jersey and netty will be optional (plus one more connection library should appear). And i will be happy to remove guava. Guava is breaking compatibility between almost every release and causes a lot of pain for everybody.

**Comment by bmuschko** [comment]
I don't see anyone working on this in the foreseeable future. Closing the issue for now.

**Comment by cdancy** [comment]
Fair enough. It's a big undertaking and the docker-java library has been working well enough
