### ISSUE TITLE
What is the best way to extract all tags on an image, starting with an existing tag

### ISSUE THREAD

**Issue by hirowla** [bmuschko/gradle-docker-plugin#727]
What is the best way to get all tags on a particular image, starting from a given tag (if I had the image ID originally I imagine this wouldn't be a problem).

Here are some tasks I came up with - the first one gets the image ID, the 2nd one is meant to get the rest of the details (the "dockerSourceTagName" variable is defined above and is valid).

```
    task getImageIdForName(type: DockerListImages) {
        imageName = dockerSourceTagName

        Action<Object> action = new Action<Object>() {
            @Override
            void execute(Object image) {
                println "Image ID is: " + image.id
                ext.extractedImageId = image.id
            }
        }
        nextHandler = action
    }

    task getImageTags(type: DockerInspectImage) {
        imageId = ext.extractedImageId
    }

```
When I run "gradlew getImageForName getImageTags", it complains that the "extractedImageId" variable doesn't exist - but as you can see, I set it above.

Am I missing something obvious?

Thanks.

**Comment by cdancy** [comment]
Does the println actually execute?

**Comment by hirowla** [comment]
If I remove the 2nd task, it definitely runs. I've tried various different options for the 2nd task but can't get the imageId from the first task to appear in the 2nd task,

**Comment by bmuschko** [comment]
The action is executed during Gradle's execution phase. That means that the extra property won't exist until the task action is executed because that's where you define it. The task `getImageTags` assigns the extra property during the configuration phase which is too early.

Here's what you should do:

1. Implement your own task type. Do not use one of the existing types that comes with plugin. Implement a task of type `AbstractDockerRemoteApiTask `. In the task implementation add a field of type `Property<String>` that represents the `extractedImageId`. In the action use the DockerClient and make a similar call to like the `DockerListImages` task. Set the property value with the `set` method of `Property`.
2. In `getImageTags` assign the `Property` field to Property `imageId` by `imageId.set(extractedImageId)`.

Ultimately, you are asking about the usage of the lazy evaluation API. The Gradle core [user guide chapter ](https://docs.gradle.org/current/userguide/lazy_configuration.html)should give you more information.

**Comment by bmuschko** [comment]
I added an example in https://github.com/bmuschko/gradle-docker-plugin/commit/ac897c7039482d3e5077158e34e2a60207baaff0
