### ISSUE TITLE
Use @CompileStatic in all classes

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-docker-plugin#759]
### Expected Behavior

Static compilation with Groovy is performed for all classes in the code base. Alternatively, just implement the whole plugin in Java.

### Current Behavior

`@CompileStatic` only applies to the class that apply the annotation. It is not inherited in subclasses. Due to this limitation, almost all custom tasks do not use static compilation even though the parent class `AbstractDockerRemoteApiTask` uses it.

### Context

Catch compilation issues early (especially when calling classes from the Docker Java library which changes its API often).

**Comment by eladchen** [comment]
Hi, 

I'm curious, are you planing on porting the entire code base to Java? (I think that is a good idea)

**Comment by bmuschko** [comment]
I would personally like the code base to be Java as you will eliminate potential binary compatibility with Groovy (bundled with a specific Gradle version). For more info see ["Prefer using a statically-typed language to implement a plugin"](https://guides.gradle.org/designing-gradle-plugins/#prefer_using_a_statically_typed_language_to_implement_a_plugin). I won't have time to work on it though as it will be quite some effort. Generally speaking, `@CompileStatic` should do the same job.

**Comment by bmuschko** [comment]
Forgot to mention. Definitely let us know if anyone feels strongly about converting the plugin code to Java. We are happy to accept pull requests. Let's chat first though as it will 1) require significant work and 2) there might be arguments speaking against it.

**Comment by eladchen** [comment]
I just spent the last ~two months implementing a plugin for the entire R&D group in my workplace.

When I started, I was also contemplating whether my work should be done in Groovy or Java
Eventually, I choose Java as it was the better (I can talk about the arguments in private)

The reason I'm sharing this with you is because I'm considering getting more involved as a contributor in the open source world, maybe this project will be entrypoint for me.

I feel like I can definitely start off with some small stuff, and when I feel like I know enough about the code base, assist with the documentation & Migrating to Java.

WDYT?

**Comment by bmuschko** [comment]
> Eventually, I choose Java as it was the better choice (I can talk about the arguments in private)

I guess that's always a matter of perspective. There's a lot of hate for Groovy these days which I believe is mostly based on its dynamic typing functionality. I definitely like Groovy a lot but there are definitely arguments for implementing Gradle plugins in Java.

> The reason I'm sharing this with you is because I'm considering getting more involved as a contributor in the open source world, maybe this project will be entrypoint for me.

Yes, please! The plugin has become quite popular. A good way to get started is by either improving documentation or going through existing issues (and implement fixes as necessary). At least from my perspective we could use more help. Pinging @cdancy @orzeh here - they are the main committers right now. WDYT?

**Comment by orzeh** [comment]
TBH I don't see any advantage of moving to Java at this stage. It's better to work on new features and improvements.

**Comment by cdancy** [comment]
@eladchen we're always looking for new contributors to the plugin and folks to come on as collaborators. If that's something you think you would be interested in I would do the following:

1. Look over our code base and get a good feel for how things look and work.
2. If there are any outstanding ISSUE's/PR's that need help feel free to jump in and help out.
3. If there are any parts of the code base you'd like to improve then just jump in and do so.
4. Anything else which might help the project in some fashion or just ask if you're short on ideas.

Once we are all more familiar with your work, and you've built up a good reputation, then we can further talk about giving you collaborator permissions.

**Comment by rkrisztian** [comment]
I personally do not see much benefit in picking a statically typed language or forcing every line to have static types. The way I see it, compatibility issues can happen either way, just the reasons of the errors may not be as obvious. And just as much as it would actually help to work with static types, you might also lose the benefit of backwards-compatible API changes of the kind that is transparent to dynamically typed callers.

Your automated tests, if written well, can verify that your code is working and nothing broke, regardless of static or dynamic typing. You can't foresee the future, where anything so it's futile to try and defend yourself against that.

To me the true benefit of `@CompileStatic` is getting as close to the speed of Java as we can, while still being able to write relatively concise code. Which is a problem for long-running Groovy scripts/classes executing, I don't know, thousands of method calls, however, Gradle builds are rather I/O bound or have other problems like bad up-to-date checks, etc., so even the performance gain of the annotation looks unimportant to me.

So the true power of static typing lies in better auto-completion for the end-user. Even in Groovy, I tend to make my public API statically typed, because that is important for them. But for internal code, I don't think that's important much. That's why I like Groovy, because it's optionally typed. I get to decide.

**Comment by bmuschko** [comment]
@rkrisztian One of the reasons I'd like to have static compilation that the Docker Java library constantly changes method signatures. It's almost impossible to write tests for every property we pass on (except if someone wanted to put in the time to do it). Knowing if the signature of a method calls changed during compilation would already help a lot in prevent issues after upgrading the Docker Java library.

Generally speaking, I don't see anyone signing up for the work from the community. I am going to close the issue and use static compilation whenever I have to touch something.

**Comment by rkrisztian** [comment]
OK, thanks for the explanation.
