### ISSUE TITLE
Support for LABEL command in the 'Dockerfile' task

### ISSUE THREAD

**Issue by steve-perkins** [bmuschko/gradle-docker-plugin#80]
We make heavy use of the LABEL command in Dockerfiles, to make it easier to understand the purpose for various images when humans browse them in our Docker Hub repo.  Long story short, we are using the 'Dockerfile' Gradle task to build our Dockerfiles dynamically... and it appears that LABEL is not one of the commands supported by this task.

I would be more than happy to submit a pull request implementing this command, simply patterned after the other 'Dockerfile.StringCommandInstruction' subclasses.  I probably need to create a fork and do this work anyway, so we'll have the LABEL support in the interim.  However, before I did so I wanted to check and be sure that this wasn't intentional... and that you haven't already contemplated some other mechanism for adding ad-hoc commands beyond those explicitly wrapped in that Gradle task now.

**Comment by bmuschko** [comment]
The [LABEL command](https://docs.docker.com/reference/builder/#label) seems more like a list of key/value pairs to me. I'd rather have a data type for it that better reflects the data structure. That's why I wouldn't want to go for a `Dockerfile.StringCommandInstruction`.

Go ahead and create pull request. We can go from there.

BTW: You can already use any implementation of `Instruction` in your build script to build your Dockerfile. It doesn't have to be part of the plugin's API.

**Comment by bmuschko** [comment]
@steve-perkins Still interested in providing a pull request?

**Comment by steve-perkins** [comment]
Apologies for the delay!  I am taking a (stay at home) vacation next week, and things have been a bit crazy getting everything squared away at work to run in my absence.  Expect a pull request on Tuesday.

**Comment by steve-perkins** [comment]
A pull request has been submitted:

https://github.com/bmuschko/gradle-docker-plugin/pull/86

I've added detailed comments on specific lines within that PR, and can discuss further either here or there.  Thanks!

**Comment by steve-perkins** [comment]
I see that the pull request was merged.  Closing this issue.  Thanks!
