### ISSUE TITLE
springBootApplication does not include custom resources

### ISSUE THREAD

**Issue by abendt-mhp** [bmuschko/gradle-docker-plugin#848]
our spring boot app build uses some generated resources. when building a bootJar (using spring boot plugin) these resources end up in the JAR in the path _BOOT-INF/classes_.

when using this plugin (springBootApplication extension/dockerBuildImage task) the generated resources do not seem to end up in the resulting image.

### Expected Behavior

i would expect custom generated gradle resources to be included in the resulting image

### Current Behavior

custom generated gradle resources are not included in the resulting image

### Context

i am currently trying to migrate an existing build from a jar deployment towards a docker deployment and want to build the docker image using this plugin

### Steps to Reproduce (for bugs)

https://github.com/abendt/gradle-dockerplugin-resources-bug

* build a bootJar: `gradlew bootJar`
* note that the generated resources end up in the jar: `unzip -l build/libs/*.jar`
* build a image: `gradlew dockerBuildImage`
* start the container
* run a shell in the container: `docker exec -ti <containerId> /bin/sh`
* note that the generated resources are not in the image: `find . -name generated.properties`

### Your Environment

```
$ gw --version
Using gradle at '/Users/abendt/Projects/spring-docker-resources/gradlew' to run buildfile '/Users/abendt/Projects/spring-docker-resources/build.gradle.kts':


------------------------------------------------------------
Gradle 5.5.1
------------------------------------------------------------

Build time:   2019-07-10 20:38:12 UTC
Revision:     3245f748c7061472da4dc184991919810f7935a5

Kotlin:       1.3.31
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.2 (Azul Systems, Inc. 11.0.2+9-LTS)
OS:           Mac OS X 10.14.6 x86_64
```

**Comment by bmuschko** [comment]
The Docker Spring Boot application plugin doesn't build a JAR anymore. The produced Docker image adds external dependencies, resource files and classes as individual image layers so that layer caching can be leveraged as much as possible. If you want to add something else, then you'll need to add an instruction to the `Dockerfile` task. For more information, see https://bmuschko.github.io/gradle-docker-plugin/#modifying_instructions_of_a_dockerfile_task. If you want to build a JAR for your Spring Boot application and include that into your Docker image, then you'll have to write your adaption of the plugin.
