### ISSUE TITLE
Use locally installed docker

### ISSUE THREAD

**Issue by cdalexndr** [bmuschko/gradle-docker-plugin#850]
On windows, exposing the docker API port without TLS poses some security risks [(source](https://www.blackhat.com/docs/us-17/thursday/us-17-Cherny-Well-That-Escalated-Quickly-How-Abusing-The-Docker-API-Led-To-Remote-Code-Execution-Same-Origin-Bypass-And-Persistence_wp.pdf)) and is disabled by default and comes with a warning if you want to enable it.

An option to use the locally installed docker commands instead of the API would be useful.

**Comment by cdancy** [comment]
While I understand your concern this plugin primarily targets the socket/port so that it can invoked from anywhere no matter if your system has docker locally installed or not. For windows the proper solution would be to run against its npipe but that support is not yet baked into the `docker-java` library we used behind the scenes.

But long story short: that would require an entire overhaul of the library and IMO not something that should be going into this library.
