### ISSUE TITLE
Groovy commands involving stages do not seem to work

### ISSUE THREAD

**Issue by Bartman0** [bmuschko/gradle-docker-plugin#907]
### Expected Behavior

I was expecting to define a multi-stage docker build using Groovy statements.
However, I could not get it work with statements like I found in the test cases:
   from('golang', 'confd')
   copyFile('/go/bin/confd', '/opt/confd/bin/', 'confd')

What am I missing here?

### Current Behavior

During building, the from() statement can not be resolved.

I currently use:
   from(new From('golang').withStage('confd'))
   copyFile(new CopyFile('/go/bin/confd', '/opt/confd/bin/').withStage('confd'))

### Your Environment

macOS 10.14.6
gradle 6.1
java version "11.0.1" 2018-10-16 LTS

**Comment by bmuschko** [comment]
In a build script, you'll have to import the class `Dockerfile`. `From` is an inner class of the task `Dockerfile`. Therefore, your statement would have to say `new Dockerfile.From`. You can find a functional test here: https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/tasks/image/DockerfileFunctionalTest.groovy#L311.

**Comment by Bartman0** [comment]
I understand, but I think we are on different pages.

This does not work:

from 'golang', 'confd'

> Could not find method from() for arguments [golang, confd] on task ':createDockerfile' of type com.bmuschko.gradle.docker.tasks.image.Dockerfile.

This does:

from(new From('golang').withStage('confd'))

I indeed imported com.bmuschko.gradle.docker.tasks.image.Dockerfile.From


The same goes for:

copyFile(new CopyFile('/go/bin/confd', '/opt/confd/bin/').withStage('confd'))    // works

but I would like to get the simpler syntax working:

copyFile '/go/bin/confd', '/opt/confd/bin/', 'confd'    // does not work


I seem to be missing something here. I saw that the ‘other’ syntax worked before, but that the functional tests now only perform the ‘Java/Groovy way of working’.
Has support for constructions like “from 'golang', 'confd'” been dropped?


Regards,


Richard.

**Comment by bmuschko** [comment]
Could you please provide more information?

- Did you recently upgrade the plugin version? If yes, please provide original version and current version. The API did change over time.
- Please provide the error message and stack trace.
- Initially, you said "During building, the from() statement can not be resolved." but then you mention that the `copyFile` method doesn't work for you. Seems like your issue shifted or you could get past your initial issue?

Please reference the Groovydocs. It should answer your question on what signature can be called for each method. For example: https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/Dockerfile.html#copyFile(java.lang.String,%20java.lang.String). As you can see, the method `copyFile '/go/bin/confd', '/opt/confd/bin/', 'confd'` is not available. The reason is that a long list of parameters can easily become incomprehensible.

**Comment by Bartman0** [comment]
Thanks for your answers. That explains it: I was looking at old examples, which I also could not explain looking at the docs.
Case closed.
