### ISSUE TITLE
Warning -  Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

### ISSUE THREAD

**Issue by paulnuk** [bmuschko/gradle-docker-plugin#919]
Running /gradlew --warning-mode all dockerBuildImage gives warning messages about features that are deprecated and are due to be removed in Gradle 7

### Expected Behavior

Running the  dockerBuildImage task should not generate warnings about deprecated features

### Current Behavior

Running ./gradlew --warning-mode all dockerBuildImage gives the following warnings:

Task :dockerCreateDockerfile UP-TO-DATE
Property 'instructions.$3.file' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'instructions.$4.file' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'instructions.$5.file' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.

### Context

Need to fix so that the plugin will work in Gradle 7

### Your Environment

Ubuntu LTS 18, Open JDK 8

**Comment by bmuschko** [comment]
My guess is that Gradle doesn't discover this input/output annotations correctly. The field `instruction` is annotated with `@Nested`, however, it's not a class, it's an interface. `FileInstruction` is an implementation of that interface. I think that trips up Gradle's checks.

Would you be interested in investigating further and/or confer with the Gradle team on this?

**Comment by paulnuk** [comment]
I've raised an issue with the Gradle developers here:

https://github.com/gradle/gradle/issues/12243

**Comment by bmuschko** [comment]
@paulnuk We'll see what the Gradle teams says. My comment was more based on a theory than an actual proof. ;-) It would require a bit of digging but maybe I am right.

**Comment by bmuschko** [comment]
Please also add your task definition and the Gradle version so someone can reproduce the issue.

**Comment by lptr** [comment]
Hey, Gradle person here. Gradle will scan the implementation type, not the declared type, so it is behaving as intended here I think (though I wasn't able to find `FileInstruction` yet). The goal of this warning is to ensure that no input or output is forgotten, and is doing it here.

**Comment by bmuschko** [comment]
@lptr `FileInstruction` is an inner class. You can find it [here](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy#L1123).`FileInstruction` implements the [interface `Instruction`](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy#L901) which declares all the input/output annotations. From what I understand from your comment, the implementation in Gradle core has changed so that only implementations are analyzed to identify if annotations have been set properly? I don't think this was an issue in earlier version of Gradle.

**Comment by lptr** [comment]
`Instruction` does not declare all the input/output annotations, as `FileInstruction` add a `getFile()` method without annotations:

https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/Dockerfile.groovy#L1135-L1137

Gradle analyzes the full type hierarchy, so annotations declared in `Instruction` are picked up as expected. The (relatively) new behavior is that after Gradle 4.5 (I think; it's been some time since we added this) we don't just analyze the declared return type of the property, but also the actual runtime type of the returned value.

**Comment by bmuschko** [comment]
Got it. You are right. Thanks for pointing that out!

**Comment by bmuschko** [comment]
@paulnuk Are you interested in working on a fix?

**Comment by paulnuk** [comment]
> @paulnuk Are you interested in working on a fix?

Sorry, I don't know Groovy nor have I written a gradle plugin before.
