### ISSUE TITLE
No documentation for DockerPushImage

### ISSUE THREAD

**Issue by softwareplumber** [bmuschko/gradle-docker-plugin#958]
The documentation for the DockerPushImage API is corrupt, there is no related DSL documentation and I can find no example anywhere from which I can glean the necessary information.

It's a real shame because the documentation and examples for building dockerfiles, building images, and so on are great. Took 10 minutes to get that stuff all working. Then an hour of futile googling when it came to doing the 'push'.  Can find lots of instances of other people failing to push stuff to a private repo but cutting and pasting their solutions does not seem to work for me.

Please can you just extend the samples to include pushing an image to a private repository?

**Comment by cdancy** [comment]
@softwareplumber what exactly is "corrupt" about it? There are loads of tasks to use here and not every single one of them is documented in detail. I suspect your frustration is coming from the fact that you may be new to gradle in general and so are unfamiliar with looking through plugin projects and where to find code and how to use it. Once you get the basic idea they are all the same.

For example: you could just dig through the source and find the task [HERE](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.groovy) and see what options are available. Or you could search the projects functional tests looking for references of `DockerPushImage`. Or, and this is my favorite, you could use the github search bar located in the top left hand corner of this very page and put in `DockerPushImage` which will bring you to various places where the task is referenced and used.

If none of those however work for you, and you're looking for something better, this is an open-source project and we love to take contributions from any and everyone. If you look through the commits you'll see we have a wide range of committers with some just sending in a PR for what they need and then never touching the project again. We have others who will provide things of this very nature (doc fixes/cleanups/etc). Would you like to send in a PR with the fix you had in mind? Maybe you've stumbled upon something the community could use and find very helpful.

**Comment by softwareplumber** [comment]
I wasn't kidding when I said I spend an hour googling a solution. I also went all through all the sample code looking for an example. I also spend a long time going through https://github.com/bmuschko/gradle-docker-plugin/issues/708 which is about the only thing which turned up that was vaguely helpful.

The documentation here https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.html is corrupt in the sense that the @InheritDoc is not being processed and is visible in the output. This makes the docs for this little more than a statement of what properties exist.

I will make a general observation - I'm not new to gradle, but becoming fully conversant with groovy is a long way down my own list of things to do. I know it is perfectly obvious to you how a given java API maps to the groovy DSL, but to me (and I daresay a decent fraction of the Gradle user base) figuring out how to actually use an API in a real script can be a question of trial-and-error, head-scratching, and frustration.  

I don't ask for perfect documentation. A 10-line example is often more useful anyway.

I'm really not the person to write that example for you. Because it needs to be a *minimal* example. I have kinda sorta got it working now, based on #708. But I'm not sure if a separate task to tag the image with the repository is really necessary. If this could be done in the build step it would be simpler. It looks like the DockerPushImage API has changed anyway since #708 because imageName= didn't work for me and images.add(...) did. Regrettably I have my own users hectoring me to fix bugs in my own code and don't have time to experiment.

I strongly urge you to add something to the sample code at least. Pushing an image to a repository is a fundamental task and deserves documentation at least as good as that which exists for building an image.

**Comment by bmuschko** [comment]
> The documentation here https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.html is corrupt in the sense that the @inheritdoc is not being processed and is visible in the output. This makes the docs for this little more than a statement of what properties exist.

I personally would call something corrupt if it is not accessible or readable at all. Seems like this is a bug in Groovy: [GROOVY-3782](https://issues.apache.org/jira/browse/GROOVY-3782). Turning the code base into plain Java would be a lot of work. [I was thinking about it](https://github.com/bmuschko/gradle-docker-plugin/issues/759) but didn't go for it for two reasons:

1. The amount of work without little benefit.
2. Some of the code still uses dynamic Groovy languages features.

The field that is of importance in the class is `images` which IMHO is properly documented: https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/image/DockerPushImage.html#images

> I will make a general observation - I'm not new to gradle, but becoming fully conversant with groovy is a long way down my own list of things to do. I know it is perfectly obvious to you how a given java API maps to the groovy DSL, but to me (and I daresay a decent fraction of the Gradle user base) figuring out how to actually use an API in a real script can be a question of trial-and-error, head-scratching, and frustration.

I have heard this argument many times before. I understand where people are coming from but ultimately it only require some fundamental knowledge to be able to make that connection. Ultimately, you are calling the Gradle API from a build script. Sometimes, the syntax may contribute to the confusion but it's rather because of Groovy language features e.g. optional parenthesis etc. My book "Gradle in Action" has a [chapter](https://livebook.manning.com/book/gradle-in-action/appendix-b?origin=product-toc) on the topic which may help.

> I don't ask for perfect documentation. A 10-line example is often more useful anyway.

General statement: Tagging a Docker image so that i can be published to private repositories is core Docker knowledge. This project shouldn't be the educator for that kind of knowledge. I understand that an example would be helpful but here are the reasons why it doesn't exist  at this time.

1. Which specific product would you document? Do we document Artifactory, GCR, ECR, etc...or all of them?
2. Almost all code snippets in the plugin user guide are automatically tested to ensure that they work. This requires actually running the operation...optimally. I don't access to any of those products and therefore we cannot ensure that the documentation is correct.

> Regrettably I have my own users hectoring me to fix bugs in my own code and don't have time to experiment.

I understand but we have the same issue. This plugin is a fun project but it doesn't pay the bills. The maintainers of this plugin all have full time jobs. In case this project would offer [GitHub Sponsorship](https://github.com/sponsors), would you be willing to donate? Instead of contributing time, it would be a way to encourage maintainers of the plugin to put in more time and focus on the features users want.

> I strongly urge you to add something to the sample code at least.

Would love to but at the moment my time is spare.

**Comment by bmuschko** [comment]
Note to self: https://github.com/bmuschko?package_type=Docker&tab=packages could be an option though I am not sure if it exposes the Docker daemon.

**Comment by softwareplumber** [comment]
The explicit tag-then-push mechanism, as you note, is core docker behavior (I've been using docker *literally* since it was invented) but is not standard at all compared to other gradle/maven mechanics for pushing artifacts. I completely agree it's impossible to document precisely how to push to every type of repository out there. But the various repos mostly differ with respect to authentication and this is a detail most people out there looking to automate docker builds will already be familiar with. One example would do.

Happy to see this issue closed as I'm up and running now.
