### ISSUE TITLE
Registry Credentials found in config.json Might be old

### ISSUE THREAD

**Issue by andrewsavino1** [bmuschko/gradle-docker-plugin#994]
### Expected Behavior
When running a dockerPushImage or PullImage, I would have expected that the plugin would use the credentials located in the docker config file at the present time.

### Current Behavior
Currently, it appears that the RegistryAuthLocator Object instantiated in these classes is created when gradle starts.  When running a more complex build with multiple gradle calls, the gradle daemon can store the config contents for too long, resulting in stale credentials.

### Context
I was able to get around this issue by running `./gradlew --stop` before running the gradle tasks that use this plugin. 

### Steps to Reproduce (for bugs)
This is a WIP: I need to verify this correctly reproduces the issue -- 

1. Create a config.json file with invalid credentials
2. Run `./gradlew <task>` to run a task that pulls/pushes to the reigstry with the invalid credentials
3. Change the invalid creds in config.json to a valid authentication
4. Run `./gradlew <task>` again -- this should still fail
5. Run `./gradlew --stop`
6. Run `./gradlew <task>` a third time -- this should succeed.

### Your Environment
I experienced this on version 6.6.1.

**Comment by bmuschko** [comment]
My guess is that we hang on to the instance of `RegistryAuthLocator ` because of the `@Memoized` annotation [here](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/tasks/AbstractDockerRemoteApiTask.groovy#L194). I don't think this shouldn't cause avoiding to read the configuration every time we access it.

Do you want to have a deeper look? I won't have the time to look into it.

**Comment by bmuschko** [comment]
I am going to close this issue for now. Please let me know if you'd like to contribute.
